### ISSUE TITLE
KairosDB 50/50 read insert workload RuntimeException

### ISSUE THREAD

**Issue by cgmcintyr** [TSDBBench/YCSB-TS#10]
<details id="testworkload">
<summary>testworload</summary>
<p>

```
workload=com.yahoo.ycsb.workloads.CoreWorkload
recordcount=1000
operationcount=1000
insertstart=1439241005000
insertend=1439242005000
measurementtype=histogram
tagvaluelength=10
tagprefix=TAG
tagcount=3
randomtagamount=false
predefinedtagvalues=true
predefinedtagvalueamount=100
predefinedtagstoragefile=predefinedtags.txt
valuemax=10000
valuemin=0
readproportion=0.5
insertproportion=0.5
scanproportion=0
avgproportion=0
countproportion=0
sumproportion=0
timevalue=0
timeunit=s
requestdistribution=uniform
maxscanlength=1000
minscanlength=500
scanlengthdistribution=uniform
maxrecordsperts=10
randomamountperts=constant
randomfloorfilling=false
querymaxtagvalues=1
notagsforread=true
readfromcsv=false
csvfile=values.csv
csvbuffersize=100000
description=Workloaddescription
timeresolution=1000
```
</p>
</details>
<br>

When checked out on `master` branch at https://github.com/TSDBBench/YCSB-TS/commit/632cd00ce72f6c20ca2786b7603464d86d8f0c0c, running the above `testworkload` on a single node cassandra-backed local kairosdb (https://github.com/kairosdb/kairosdb/releases/tag/v1.2.0) instance results in the following error:

```
$ ./bin/ycsb run kairosdb -P workloads/testworkloada -p "port=8080" -p "ip=127.0.0.1"
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:kairosdb-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /home/cgmcintyre/devel/uni/dissertation/kairos-db-scylla/YCSB-TS/kairosdb/conf:/home/cgmcintyre/devel/uni/dissertation/kairos-db-scylla/YCSB-TS/kairosdb/target/kairosdb-binding-0.4.0.jar:/home/cgmcintyre/.m2/repository/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/cgmcintyre/.m2/repository/com/google/guava/guava/14.0/guava-14.0.jar:/home/cgmcintyre/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/cgmcintyre/.m2/repository/com/google/code/findbugs/jsr305/2.0.0/jsr305-2.0.0.jar:/home/cgmcintyre/.m2/repository/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/cgmcintyre/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/cgmcintyre/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar:/home/cgmcintyre/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/cgmcintyre/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/cgmcintyre/devel/uni/dissertation/kairos-db-scylla/YCSB-TS/core/target/core-0.4.0.jar:/home/cgmcintyre/.m2/repository/net/sourceforge/javacsv/javacsv/2.0/javacsv-2.0.jar:/home/cgmcintyre/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/cgmcintyre/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/home/cgmcintyre/.m2/repository/org/kairosdb/client/2.0/client-2.0.jar:/home/cgmcintyre/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.KairosDBClient -P workloads/testworkloada -p port=8080 -p ip=127.0.0.1 -t
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.KairosDBClient -P workloads/testworkloada -p port=8080 -p ip=127.0.0.1 -t
Loading workload...
[DESCRIPTION], Workloaddescription
Starting test.
WARNING: INSERT inside RUN phase is untested!.
WARNING: INSERT inside RUN phase is untested!.
java.lang.RuntimeException: Too many unacknowledged insertion keys.
	at com.yahoo.ycsb.generator.AcknowledgedCounterGenerator.acknowledge(AcknowledgedCounterGenerator.java:65)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:1027)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:949)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)
java.lang.RuntimeException: Too many unacknowledged insertion keys.
	at com.yahoo.ycsb.generator.AcknowledgedCounterGenerator.acknowledge(AcknowledgedCounterGenerator.java:65)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:1027)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:949)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)

```

**Comment by seanlook** [comment]
It seems not resolved yet. I'm testing opentsdb, the load phase is ok but not run.

`load` is `run` in YCSB-TS?
